apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing
  namespace: default
  labels:
    app: landing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landing
  template:
    metadata:
      labels:
        app: landing
    spec:
      containers:
        - name: landing
          image: ghcr.io/richardtan10176/landing:f56fe05e6ed0f7822d6d86772f49f1ab7cfbd8bb
          ports:
            - containerPort: 80
