apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing
  namespace: default
  labels:
    app: landing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landing
  template:
    metadata:
      labels:
        app: landing
    spec:
      containers:
        - name: landing
          image: ghcr.io/richardtan10176/landing:bbf4629b1ea74d23725442fe11574d9b1e148175
          ports:
            - containerPort: 80
