apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-site
  namespace: default
  labels:
    app: hello-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-site
  template:
    metadata:
      labels:
        app: hello-site
    spec:
      containers:
        - name: hello-site
          image: ghcr.io/richardtan10176/hello-site:09062a8fa4342333d996b0187fff4a1351faedec
          ports:
            - containerPort: 80
